COPY	START	1000
FIRST	STL		RETADR
CLOOP	JSUB	RDREC
		LDA		LENGTH
		COMP	ZERO
		JEQ		ENDFIL
		JSUB	WRREC
		J		CLOOP
ENDFIL	LDA		EOF
		STA		BUFFER
		BYTE	X'123
		LDA		TREE
		STA 	LENGHT
		JSUB	WRREC
		LDL		RETADR
		RSUB
BYTE	BYTE	C'11'
EOF		BYTE	C'EOF'
TREE	WORD	000003
ZERO	WORD	000000
        END		